# curl -X POST "http://127.0.0.1:5000/get-response" -H "Content-Type: application/json" -d '{"message": "Какая столица Франции?"}'
POST http://127.0.0.1:5000/get-response
Content-Type: application/json

{
  "message": "Какая столица Франции?"
}

###

